from .fixtures import (
    add_vaccine_batch,
    authenticate_api,
    base_url,
    basic_auth_credentials,
    basic_auth_token,
    browser_context_args,
    browser_type,
    children,
    create_child,
    delete_teams_after_tests,
    log_in_as_medical_secretary,
    log_in_as_nurse,
    log_in_as_prescriber,
    national_reporting_file_generator,
    national_reporting_healthcare_assistant,
    national_reporting_medical_secretary,
    national_reporting_nurse,
    national_reporting_onboarding,
    national_reporting_organisation,
    national_reporting_prescriber,
    national_reporting_superuser,
    national_reporting_team,
    point_of_care_clinics,
    point_of_care_file_generator,
    point_of_care_healthcare_assistant,
    point_of_care_medical_secretary,
    point_of_care_nurse,
    point_of_care_onboarding,
    point_of_care_organisation,
    point_of_care_prescriber,
    point_of_care_subteam,
    point_of_care_superuser,
    point_of_care_team,
    reset_before_each_module,
    schedule_mmr_session_and_get_consent_url,
    schedule_mmrv_session_and_get_consent_url,
    schedule_session_and_get_consent_url,
    schools,
    set_feature_flags,
    setup_logged_in_session_with_file_upload_for_programme,
    setup_national_reporting_import,
    setup_session_and_batches_with_fixed_child,
    upload_offline_vaccination,
    year_groups,
)
from .hooks import pytest_sessionfinish, pytest_sessionstart

# Note: Jira integration hooks are now provided by pytest-jira-zephyr-reporter package
# and auto-register via pytest entry points.
# Explicit imports below for backwards compatibility.
try:
    from pytest_jira_zephyr_reporter.hooks import (
        pytest_configure,
        pytest_runtest_makereport,
        pytest_runtest_setup,
        pytest_runtest_teardown,
    )
except ImportError:
    # If package is not installed, define no-op hooks
    pytest_configure = None
    pytest_runtest_makereport = None
    pytest_runtest_setup = None
    pytest_runtest_teardown = None

__all__ = [
    "add_vaccine_batch",
    "authenticate_api",
    "base_url",
    "basic_auth_credentials",
    "basic_auth_token",
    "browser_context_args",
    "browser_type",
    "children",
    "create_child",
    "delete_teams_after_tests",
    "log_in_as_medical_secretary",
    "log_in_as_nurse",
    "log_in_as_prescriber",
    "national_reporting_file_generator",
    "national_reporting_healthcare_assistant",
    "national_reporting_medical_secretary",
    "national_reporting_nurse",
    "national_reporting_onboarding",
    "national_reporting_organisation",
    "national_reporting_prescriber",
    "national_reporting_superuser",
    "national_reporting_team",
    "point_of_care_clinics",
    "point_of_care_file_generator",
    "point_of_care_healthcare_assistant",
    "point_of_care_medical_secretary",
    "point_of_care_nurse",
    "point_of_care_onboarding",
    "point_of_care_organisation",
    "point_of_care_prescriber",
    "point_of_care_subteam",
    "point_of_care_superuser",
    "point_of_care_team",
    "pytest_configure",
    "pytest_configure",
    "pytest_runtest_makereport",
    "pytest_runtest_makereport",
    "pytest_runtest_setup",
    "pytest_runtest_teardown",
    "pytest_sessionfinish",
    "pytest_sessionstart",
    "reset_before_each_module",
    "schedule_mmr_session_and_get_consent_url",
    "schedule_mmrv_session_and_get_consent_url",
    "schedule_session_and_get_consent_url",
    "schools",
    "set_feature_flags",
    "setup_logged_in_session_with_file_upload_for_programme",
    "setup_national_reporting_import",
    "setup_session_and_batches_with_fixed_child",
    "upload_offline_vaccination",
    "year_groups",
]
