repos:
- repo: local
  hooks:
  - id: scan-secrets
    name: Scan secrets
    entry: ./scripts/githooks/scan-secrets.sh
    args: ["check=staged-changes"]
    language: script
    pass_filenames: false
