name: "Generate and Deploy Report"
description: "Generates Allure report and uploads to S3"
inputs:
  device:
    required: true
  environment:
    required: true
  s3-bucket:
    required: true
    default: 'endtoendtest-reports'
  report-base-url:
    required: true
    default: 'https://d2h72ta68jwsgq.cloudfront.net'
runs:
  using: composite
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'

    - name: Generate Allure report
      run: npx allure-commandline generate allure-results -o allure-report
      shell: bash
      continue-on-error: true

    - name: Set S3 prefix
      id: set-pages-dir
      run: |
        branch_ref="${{ github.head_ref || github.ref_name }}"
        sanitized_device=$(echo "${{ inputs.device }}" | tr -cd '[:alnum:]_-')
        timestamp=$(date -u +"%Y-%m-%d_%H-%M-%S")
        echo "dir=$branch_ref/${{ inputs.environment }}/$sanitized_device/$timestamp" >> $GITHUB_OUTPUT
      shell: bash

    - name: Upload report to S3
      run: |
        aws s3 sync \
          allure-report \
          s3://${{ inputs.s3-bucket }}/${{ steps.set-pages-dir.outputs.dir }} \
          --delete
      shell: bash

    - name: Set Job Summary
      run: |
        REPORT_URL="${{ inputs.report-base-url }}/${{ steps.set-pages-dir.outputs.dir }}/index.html"
        echo "View test report: ${REPORT_URL}" >> "$GITHUB_STEP_SUMMARY"
      shell: bash
