name: Functional tests (selected device)

on:
  workflow_dispatch:
    inputs:
      device:
        description: 'Device to test (exact name)'
        required: false
        default: 'Desktop Chrome'
      environment:
        description: 'Environment to run tests on (qa, test, training)'
        required: false
        default: 'qa'
  pull_request:

jobs:
  test:
    permissions:
      contents: write
    
    name: Test

    runs-on: ubuntu-latest

    env:
      TZ: "Europe/London"

    steps:
      - uses: actions/checkout@v4
      
      - name: Set device variable
        id: set-device
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "device=Desktop Chrome" >> $GITHUB_OUTPUT
          else
            echo "device=${{ github.event.inputs.device }}" >> $GITHUB_OUTPUT
          fi

      - name: Set environment
        id: set-environment
        run: |
          declare -A env_map=(
            [qa]="https://qa.mavistesting.com"
            [test]="https://test.mavistesting.com"
            [training]="https://training.manage-vaccinations-in-schools.nhs.uk"
          )
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "environment=${env_map[qa]}" >> $GITHUB_OUTPUT
          else
            input_env="${{ github.event.inputs.environment }}"
            url="${env_map[$input_env]:-${env_map[qa]}}"
            echo "environment=$url" >> $GITHUB_OUTPUT
          fi

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install Playwright
        run: uv run playwright install --with-deps

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run tests
        run: uv run pytest --device "${{ steps.set-device.outputs.device }}"
        env:
          BASE_URL: ${{ steps.set-environment.outputs.environment }}
          PROGRAMMES_ENABLED: ${{ vars.PROGRAMMES_ENABLED }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
          BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}

      - name: Generate Allure report
        if: always()
        run: |
          npx allure-commandline generate allure-results -o allure-report

      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          force_orphan: true
        
      
      - name: Set Job Summary
        if: always()
        run: |
          echo "Test report URL is https://nhsdigital.github.io/manage-vaccinations-in-schools-testing/" >> $GITHUB_STEP_SUMMARY
