name: Functional tests

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TZ: "Europe/London"
    strategy:
      matrix:
        location: ["UK"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: .tool-versions
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          playwright install
          playwright install-deps
      - name: Test on Chromium
        env:
          CAPTURE_SCREENSHOTS: ${{ vars.CAPTURE_SCREENSHOTS }}
          BASE_URL: ${{ vars.BASE_URL }}
          RESET_ENDPOINT: ${{ vars.RESET_ENDPOINT }}
          NURSE_PASSWORD: ${{ secrets.NURSE_PASSWORD }}
          NURSE_USERNAME: ${{ secrets.NURSE_USERNAME }}
          SUPERUSER_PASSWORD: ${{ secrets.SUPERUSER_PASSWORD }}
          SUPERUSER_USERNAME: ${{ secrets.SUPERUSER_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
          BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
        run: |
          echo "::group::Chromium"
          pytest --browser chromium
          echo "::endgroup::"
      - name: Test on Chrome
        if: always()
        env:
          CAPTURE_SCREENSHOTS: ${{ vars.CAPTURE_SCREENSHOTS }}
          BASE_URL: ${{ vars.BASE_URL }}
          RESET_ENDPOINT: ${{ vars.RESET_ENDPOINT }}
          NURSE_PASSWORD: ${{ secrets.NURSE_PASSWORD }}
          NURSE_USERNAME: ${{ secrets.NURSE_USERNAME }}
          SUPERUSER_PASSWORD: ${{ secrets.SUPERUSER_PASSWORD }}
          SUPERUSER_USERNAME: ${{ secrets.SUPERUSER_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
          BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
        run: |
          echo "::group::Chrome"
          pytest --browser chromium --browser-channel chrome
          echo "::endgroup::"
      - name: Test on Firefox
        env:
          CAPTURE_SCREENSHOTS: ${{ vars.CAPTURE_SCREENSHOTS }}
          BASE_URL: ${{ vars.BASE_URL }}
          RESET_ENDPOINT: ${{ vars.RESET_ENDPOINT }}
          NURSE_PASSWORD: ${{ secrets.NURSE_PASSWORD }}
          NURSE_USERNAME: ${{ secrets.NURSE_USERNAME }}
          SUPERUSER_PASSWORD: ${{ secrets.SUPERUSER_PASSWORD }}
          SUPERUSER_USERNAME: ${{ secrets.SUPERUSER_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
          BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
        run: |
          echo "::group::Firefox"
          pytest --browser firefox
          echo "::endgroup::"
      - name: Test on Edge
        if: always()
        env:
          CAPTURE_SCREENSHOTS: ${{ vars.CAPTURE_SCREENSHOTS }}
          BASE_URL: ${{ vars.BASE_URL }}
          RESET_ENDPOINT: ${{ vars.RESET_ENDPOINT }}
          NURSE_PASSWORD: ${{ secrets.NURSE_PASSWORD }}
          NURSE_USERNAME: ${{ secrets.NURSE_USERNAME }}
          SUPERUSER_PASSWORD: ${{ secrets.SUPERUSER_PASSWORD }}
          SUPERUSER_USERNAME: ${{ secrets.SUPERUSER_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
          BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
        run: |
          echo "::group::Edge"
          pytest --browser chromium --browser-channel msedge
          echo "::endgroup::"
      - name: Test on iPhone 14
        if: always()
        env:
          CAPTURE_SCREENSHOTS: ${{ vars.CAPTURE_SCREENSHOTS }}
          BASE_URL: ${{ vars.BASE_URL }}
          RESET_ENDPOINT: ${{ vars.RESET_ENDPOINT }}
          NURSE_PASSWORD: ${{ secrets.NURSE_PASSWORD }}
          NURSE_USERNAME: ${{ secrets.NURSE_USERNAME }}
          SUPERUSER_PASSWORD: ${{ secrets.SUPERUSER_PASSWORD }}
          SUPERUSER_USERNAME: ${{ secrets.SUPERUSER_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
          BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
        run: |
          echo "::group::iPhone 14"
          pytest -m mobile --browser webkit --device "iPhone 14"
          echo "::endgroup::"
      - name: Test on iPhone 15
        if: always()
        env:
          CAPTURE_SCREENSHOTS: ${{ vars.CAPTURE_SCREENSHOTS }}
          BASE_URL: ${{ vars.BASE_URL }}
          RESET_ENDPOINT: ${{ vars.RESET_ENDPOINT }}
          NURSE_PASSWORD: ${{ secrets.NURSE_PASSWORD }}
          NURSE_USERNAME: ${{ secrets.NURSE_USERNAME }}
          SUPERUSER_PASSWORD: ${{ secrets.SUPERUSER_PASSWORD }}
          SUPERUSER_USERNAME: ${{ secrets.SUPERUSER_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
          BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
        run: |
          echo "::group::iPhone 15"
          pytest -m mobile --browser webkit --device "iPhone 15"
          echo "::endgroup::"
      - name: Test on iPad Gen 7
        if: always()
        env:
          CAPTURE_SCREENSHOTS: ${{ vars.CAPTURE_SCREENSHOTS }}
          BASE_URL: ${{ vars.BASE_URL }}
          RESET_ENDPOINT: ${{ vars.RESET_ENDPOINT }}
          NURSE_PASSWORD: ${{ secrets.NURSE_PASSWORD }}
          NURSE_USERNAME: ${{ secrets.NURSE_USERNAME }}
          SUPERUSER_PASSWORD: ${{ secrets.SUPERUSER_PASSWORD }}
          SUPERUSER_USERNAME: ${{ secrets.SUPERUSER_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
          BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
        run: |
          echo "::group::iPad Gen 7"
          pytest -m mobile --browser webkit --device "iPad (gen 7) landscape"
          echo "::endgroup::"
      - name: Test on Samsung Galaxy S9+
        if: always()
        env:
          CAPTURE_SCREENSHOTS: ${{ vars.CAPTURE_SCREENSHOTS }}
          BASE_URL: ${{ vars.BASE_URL }}
          RESET_ENDPOINT: ${{ vars.RESET_ENDPOINT }}
          NURSE_PASSWORD: ${{ secrets.NURSE_PASSWORD }}
          NURSE_USERNAME: ${{ secrets.NURSE_USERNAME }}
          SUPERUSER_PASSWORD: ${{ secrets.SUPERUSER_PASSWORD }}
          SUPERUSER_USERNAME: ${{ secrets.SUPERUSER_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
          BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
        run: |
          echo "::group::Samsung Galaxy S9+"
          pytest -m mobile --browser chromium --device "Galaxy S9+"
          echo "::endgroup::"
      - name: Test on Google Pixel 7
        if: always()
        env:
          CAPTURE_SCREENSHOTS: ${{ vars.CAPTURE_SCREENSHOTS }}
          BASE_URL: ${{ vars.BASE_URL }}
          RESET_ENDPOINT: ${{ vars.RESET_ENDPOINT }}
          NURSE_PASSWORD: ${{ secrets.NURSE_PASSWORD }}
          NURSE_USERNAME: ${{ secrets.NURSE_USERNAME }}
          SUPERUSER_PASSWORD: ${{ secrets.SUPERUSER_PASSWORD }}
          SUPERUSER_USERNAME: ${{ secrets.SUPERUSER_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
          BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
        run: |
          echo "::group::Google Pixel 7"
          pytest -m mobile --browser chromium --device "Pixel 7"
          echo "::endgroup::"
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-reports
          path: reports
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots
