name: Functional tests (all devices on QA)

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  test:
    permissions:
      contents: write

    name: Functional tests
    strategy:
      fail-fast: false
      matrix:
        device:
          - Desktop Chrome
          - Desktop Edge
          - Desktop Firefox
          - Desktop Safari
          - Galaxy S9+
          - Pixel 7
          - iPad (gen 7) landscape
          - iPhone 15
      max-parallel: 2

    runs-on: ubuntu-latest
    env:
      TZ: "Europe/London"

    steps:
      - uses: actions/checkout@v5

      - name: Run tests
        uses: ./.github/actions/run-functional-tests
        with:
          device: ${{ matrix.device }}
          base_url: ${{ vars.BASE_URL }}
          programmes_enabled: ${{ vars.PROGRAMMES_ENABLED }}
        env:
          BASIC_AUTH_TOKEN: ${{ secrets.HTTP_AUTH_TOKEN_FOR_TESTS }}
          IMMS_BASE_URL: ${{ vars.IMMS_BASE_URL }}
          IMMS_API_KEY: ${{ secrets.IMMS_API_KEY }}
          IMMS_API_KID: ${{ secrets.IMMS_API_KID }}
          IMMS_API_PEM: ${{ secrets.IMMS_API_PEM }}

      - name: Process reports
        if: always()
        uses: ./.github/actions/deploy-reports
        with:
          device: ${{ matrix.device }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
