name: Functional tests

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  test:
    name: Test

    strategy:
      matrix:
        device:
          - Desktop Chrome
          - Desktop Edge
          - Desktop Firefox
          - Desktop Safari
          - Galaxy S9+
          - Pixel 7
          - iPad (gen 7) landscape
          - iPhone 15
      max-parallel: 2

    permissions: {}

    runs-on: ubuntu-latest

    env:
      TZ: "Europe/London"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install Playwright
        run: uv run playwright install --with-deps

      - name: Run tests
        run: uv run pytest --device "${{ matrix.device }}"
        env:
          BASE_URL: ${{ vars.BASE_URL }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
          BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.device }}
          path: allure-results
