name: Functional tests (all devices on QA)

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  test:
    permissions:
      contents: write

    name: Test

    strategy:
      fail-fast: false
      matrix:
        device:
          - Desktop Chrome
          - Desktop Edge
          - Desktop Firefox
          - Desktop Safari
          - Galaxy S9+
          - Pixel 7
          - iPad (gen 7) landscape
          - iPhone 15
      max-parallel: 2

    runs-on: ubuntu-latest

    env:
      TZ: "Europe/London"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install Playwright
        run: uv run playwright install --with-deps

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run tests
        run: uv run pytest --device "${{ matrix.device }}"
        env:
          BASE_URL: ${{ vars.BASE_URL }}
          PROGRAMMES_ENABLED: ${{ vars.PROGRAMMES_ENABLED }}
          BASIC_AUTH_TOKEN: ${{ secrets.HTTP_AUTH_TOKEN_FOR_TESTS }}
          BASIC_AUTH_USERNAME: ""
          BASIC_AUTH_PASSWORD: ""

      - name: Generate Allure report
        if: always()
        run: |
          npx allure-commandline generate allure-results -o allure-report

      - name: Set GitHub Pages directory
        if: always()
        id: set-pages-dir
        run: |
          sanitized_device=$(echo "${{ matrix.device }}" | tr -cd '[:alnum:]_-')
          echo "dir=${{ github.ref_name }}/$sanitized_device" >> $GITHUB_OUTPUT

      - name: Checkout gh-pages branch
        if: always()
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Replace existing report with new report
        if: always()
        run: |
          rm -rf gh-pages/${{ steps.set-pages-dir.outputs.dir }}
          mkdir -p gh-pages/${{ steps.set-pages-dir.outputs.dir }}
          cp -r allure-report/* gh-pages/${{ steps.set-pages-dir.outputs.dir }}

      - name: Commit and push changes
        if: always()
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ steps.set-pages-dir.outputs.dir }}
          # Only commit if there are changes
          git diff --cached --quiet || git commit -m "Deploy changes to pages"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set Job Summary
        if: always()
        run: |
          echo "Test report URL is https://nhsdigital.github.io/manage-vaccinations-in-schools-testing/${{ steps.set-pages-dir.outputs.dir }}" >> $GITHUB_STEP_SUMMARY
