name: Lint

on:
  pull_request:

permissions:
  contents: read

jobs:
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          install_args: gitleaks
          cache: true
      - name: Check for secrets
        run: gitleaks detect --verbose --redact

  uv:
    name: uv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        
      - name: Install project
        run: uv sync --locked --all-extras --dev

  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Check formatting
        run: uv run ruff format --check
      - name: Check linting
        run: uv run ruff check
