name: Lint

on:
  pull_request:

permissions:
  contents: read

jobs:
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          install_args: gitleaks
          cache: true
      - name: Check for secrets
        run: gitleaks detect --verbose --redact
