# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run MAVIS tests on TEST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 7 * * *"

permissions:
  contents: write

jobs:
  test:

    runs-on: ubuntu-latest
    env:
      TZ: "Europe/London"
    strategy:
      matrix:
        location: ['UK']


    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        playwright install
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      env:
        HEADLESS: ${{ vars.HEADLESS }}
        CAPTURE_SCREENSHOTS: ${{ vars.CAPTURE_SCREENSHOTS }}
        TEST_URL: ${{ vars.TEST_URL }}
        PARENTAL_CONSENT_URL: ${{ vars.PARENTAL_CONSENT_URL }}
        RESET_ENDPOINT: ${{ vars.RESET_ENDPOINT }}
        LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
        LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
        API_TOKEN: ${{ secrets.API_TOKEN }}
      run: |
        echo "Starting tests on Chromium"
        pytest --browser_or_device chromium
        echo "Starting tests on Chrome"
        pytest --browser_or_device chrome
        # echo "Starting tests on Firefox"
        # pytest --browser_or_device firefox
        echo "Starting tests on iPhone 12"
        pytest --browser_or_device iphone_12
        echo "Starting tests on iPhone 11"
        pytest --browser_or_device iphone_11
        echo "Starting tests on Pixel 5"
        pytest --browser_or_device pixel_5
    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: pytest-html-report
        path: reports
    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      with:
        name: screenshots
        path: screenshots
