# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run MAVIS tests on TEST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 7 * * *"

permissions:
  contents: write

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      env: 
        BROWSER: ${{ vars.BROWSER }}
        HEADLESS: ${{ vars.HEADLESS }}
        CAPTURE_SCREENSHOTS: ${{ vars.CAPTURE_SCREENSHOTS }}
        TEST_URL: ${{ vars.TEST_URL }}
        PARENTAL_CONSENT_URL: ${{ vars.PARENTAL_CONSENT_URL }}
        LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
        LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
      run: |
        pytest
