name: Consent Journey performance test

on:
  push:
    branches:
      - performance-testing

  workflow_dispatch:
    inputs:
      URN:
        description: "Required: what URN to run the test against."
        required: true
        type: string
      duration:
        description: "Optional (default 3600) Duration of consent journey test, in seconds. This will include ramp-up."
        required: false
        type: string
      threads:
        description: "Optional (default 70) Threads to run."
        required: false
        type: string
      ramp_up:
        description: "Optional (default 900) Ramp-up time in seconds. Threads will be gradually started up over this time."
        required: false
        type: string
      row_count:
        description: "Optional (default 1000) number of rows in the cohort file."
        required: false
        type: string


# env:
#   JMETER_PLUGIN_INSTALL_LIST: "jpgc-udp,jpgc-graphs-basic,jpgc-dummy,bzm-random-csv"

jobs:
  nurse_journey_performance_test:
    runs-on: ubuntu-latest

    if: ${{ github.event_name == 'workflow_dispatch' }}

    env:
      jmeter_version: 5.6.3
      cmdrunner_version: 2.3
      jmeter_plugins_manager_version: 1.7.0
      jmeter_plugins: jpgc-udp,jpgc-graphs-basic,jpgc-dummy,bzm-random-csv
      # jmeter_home: ${{ github.workspace }}/jmeter-${{ env.jmeter_version }}

    steps:
      - uses: actions/checkout@v4

      - name: Install JMeter
        run: |
          curl -sSO https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-${{ env.jmeter_version }}.tgz
          tar xzf apache-jmeter-${{ env.jmeter_version }}.tgz
          mv apache-jmeter-${{ env.jmeter_version }} jmeter
          curl -sSO --output-dir jmeter/lib https://repo1.maven.org/maven2/kg/apc/cmdrunner/${{ env.cmdrunner_version }}/cmdrunner-${{ env.cmdrunner_version }}.jar
          curl -LsS --output jmeter/lib/ext/jmeter-plugins-manager-${{ env.jmeter_plugins_manager_version  }}.jar https://jmeter-plugins.org/get/
          java -cp jmeter/lib/ext/jmeter-plugins-manager-${{ env.jmeter_plugins_manager_version }}.jar org.jmeterplugins.repository.PluginManagerCMDInstaller
          chmod +x jmeter/bin/PluginsManagerCMD.sh
          sed -i '/<Logger name="org.apache.jmeter.junit" level="debug" \/>/a \    <Logger name="org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase" level="info" additivity="false"\/>' jmeter/bin/log4j2.xml

      - name: Install JMeter plugins
        if: env.jmeter_plugins != ''
        run: |
          if [ -x "$(command -v parallel)" ]; then
            echo "Using GNU parallel to install plugins"
            parallel -d, -j 5 -n 1 jmeter/bin/PluginsManagerCMD.sh install {} ::: ${{ env.jmeter_plugins }}
          else
            echo "GNU parallel not found, installing plugins sequentially"
            IFS=',' read -ra PLUGINS <<< "${{ env.jmeter_plugins }}"
            for plugin in "${PLUGINS[@]}"; do
              jmeter/bin/PluginsManagerCMD.sh install $plugin
            done
          fi

      - name: Set timestamp
        id: timestamp
        run: echo "timestamp=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create new cohort file
        if: inputs.runDataPrep == true
        run: |
          mkdir -p generate-cohort-output
          generate_cohort_output_dir=generate-cohort-output
          jmeter/bin/jmeter -n -t performance-tests/E2E/generate-cohort.jmx \
              -l $generate_cohort_output_dir/samples.jtl \
              -j $generate_cohort_output_dir/jmeter.log \
              -e -o $generate_cohort_output_dir/upload-report \
              -JAuthToken=${{secrets.HTTP_AUTH_TOKEN_FOR_TESTS}} \
              -JURN=${{inputs.URN}} \
              -JRowCount=${{inputs.row_count}}

      - name: Run file import for new file
        if: inputs.runDataPrep == true
        run: |
          mkdir -p import-output
          import_output_dir=import-output
          jmeter/bin/jmeter -n -t performance-tests/E2E/upload-cohort-data.jmx \
              -l $import_output_dir/samples.jtl \
              -j $import_output_dir/jmeter.log \
              -e -o $import_output_dir/upload-report \
              -JAuthToken=${{secrets.HTTP_AUTH_TOKEN_FOR_TESTS}} \
              -JInputFile="cohortnew.csv"

      - name: Run Consent Journey for imported records
        if: inputs.runDataPrep == true
        run: |
          mkdir -p consent-output
          consent_output_dir=consent-output
          jmeter/bin/jmeter -n -t performance-tests/E2E/consent-journey.jmx \
              -l $consent_output_dir/samples.jtl \
              -j $consent_output_dir/jmeter.log \
              -e -o $consent_output_dir/consent-report \
              -JAuthToken=${{secrets.HTTP_AUTH_TOKEN_FOR_TESTS}} \
              -JDuration=${{inputs.duration}} \
              -JThreads=${{inputs.threads}} \
              -JRampUp=${{inputs.ramp_up}} \
              -JLoops=10000 \
              -JInputFile="cohortnew.csv"

      - name: Upload consent journey JMeter output
        if: inputs.runDataPrep == true
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-consent-journey-output-${{ env.timestamp }}
          path: consent-output
          if-no-files-found: warn
